# Generated by Django 5.1.4 on 2024-12-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponusagelog',
            old_name='coupon',
            new_name='coupon_id',
        ),
    ]
