# Generated by Django 5.1.4 on 2024-12-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_coupon_couponusagelog_coupon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponusagelog',
            old_name='coupon_id',
            new_name='coupon',
        ),
    ]
