# Generated by Django 5.1.4 on 2024-12-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_coupon_id_couponusagelog_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusagelog',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
